name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  api-go:
    name: Backend (Go)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apps/api-go

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

      - name: Run vet
        run: go vet ./...

  web-next:
    name: Frontend (Next.js)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apps/web-next

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.18.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Check types
        run: npx tsc --noEmit
